### ISSUE TITLE
Logo design template

### ISSUE THREAD

**Issue by Immortalin** [reddec/fluent-amqp#3]
The logo is really nice, do you mind sharing the template or source? The periodic table theme is quite appropriate for open source projects.

**Comment by reddec** [comment]
Already there https://github.com/reddec/fluent-amqp/blob/master/docs/logo.svg

Feel free to use it. Link to me as source of inspiration will be welcome)

**Comment by reddec** [comment]
@Immortalin I made a generator

https://reddec.net/demo/element-logo-generator/
